# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\uri42\Desktop\Date-Manger\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(960, 1240)
        dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(450, 80, 281, 61))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:rgb(255, 255, 255); font-size:20pt;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(350, 320, 61, 41))
        self.label_2.setStyleSheet("font-size:15pt; color:rgb(70, 120, 99);font-weight:600;")
        self.label_2.setObjectName("label_2")
        self.ID = QtWidgets.QLineEdit(dialog)
        self.ID.setGeometry(QtCore.QRect(430, 320, 191, 41))
        self.ID.setStyleSheet("font-size:14pt; color:rgb(255, 247, 242)")
        self.ID.setText("")
        self.ID.setObjectName("ID")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(350, 390, 71, 41))
        self.label_3.setStyleSheet("font-size:15pt; color:rgb(70, 120, 99);font-weight:600;")
        self.label_3.setObjectName("label_3")
        self.PW = QtWidgets.QLineEdit(dialog)
        self.PW.setGeometry(QtCore.QRect(430, 390, 191, 41))
        self.PW.setStyleSheet("font-size:14pt; color:rgb(255, 247, 242)")
        self.PW.setText("")
        self.PW.setObjectName("PW")
        self.Login_button = QtWidgets.QPushButton(dialog)
        self.Login_button.setGeometry(QtCore.QRect(470, 500, 121, 61))
        self.Login_button.setStyleSheet("color:rgb(255, 255, 255);background-color: rgb(167, 168, 167);font-size:14pt;")
        self.Login_button.setObjectName("Login_button")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.label.setText(_translate("dialog", "Login"))
        self.label_2.setText(_translate("dialog", "ID"))
        self.label_3.setText(_translate("dialog", "PW"))
        self.Login_button.setText(_translate("dialog", "Login"))
