# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\uri42\Desktop\Date-Manger\start_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(223, 95, 159, 200), stop:0.513812 rgba(224, 212, 107, 200), stop:1 rgba(103, 188, 228, 200))")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 230, -1, 230)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(240, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(240, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius : 10px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DM_label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Colonna MT")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.DM_label_2.setFont(font)
        self.DM_label_2.setStyleSheet("color : rgb(0, 0, 0);\n"
"background-color : rgba(255, 255, 255, 0);\n"
"\n"
"font-family : \'Colonna MT\';\n"
"font-weight : bold;\n"
"font-size : 40pt; ")
        self.DM_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DM_label_2.setObjectName("DM_label_2")
        self.verticalLayout_2.addWidget(self.DM_label_2)
        self.DM_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Colonna MT")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.DM_label.setFont(font)
        self.DM_label.setStyleSheet("color : rgb(0, 0, 0);\n"
"background-color : rgba(255, 255, 255, 0);\n"
"\n"
"font-family : \'Colonna MT\';\n"
"font-weight : bold;\n"
"font-size : 40pt; ")
        self.DM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.DM_label.setObjectName("DM_label")
        self.verticalLayout_2.addWidget(self.DM_label)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font-family : \'Dosis\';\n"
"\n"
"font-size : 12pt;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.member_num = QtWidgets.QLineEdit(self.widget)
        self.member_num.setStyleSheet("background-color: rgba(0, 0, 0, 50);\n"
"color : rgb(255, 255, 255);\n"
"\n"
"font-family : \'Dosis\';\n"
"font-size : 12pt;")
        self.member_num.setText("")
        self.member_num.setAlignment(QtCore.Qt.AlignCenter)
        self.member_num.setObjectName("member_num")
        self.horizontalLayout.addWidget(self.member_num)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setStyleSheet("color : rgb(255, 255, 255);\n"
"background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 14pt;\n"
"\n"
"border-radius : 20px;")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.DM_label_2.setText(_translate("Dialog", "<html><head/><body><p>Date</p></body></html>"))
        self.DM_label.setText(_translate("Dialog", "<html><head/><body><p>Manager</p></body></html>"))
        self.label.setText(_translate("Dialog", "How many?"))
        self.start_button.setText(_translate("Dialog", "Ready To Date?"))
