# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\uri42\Desktop\Date-Manger\Dummy Files\locate_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(223, 95, 159, 200), stop:0.513812 rgba(224, 212, 107, 200), stop:1 rgba(103, 188, 228, 200))")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(250, 60, 400, 700))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius : 10px;")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 200, 60))
        self.label_2.setStyleSheet("color : rgb(0, 0, 0);\n"
"background-color : rgb(255, 255, 255);\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 26pt; ")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Submit_button = QtWidgets.QPushButton(self.widget)
        self.Submit_button.setGeometry(QtCore.QRect(50, 570, 300, 40))
        self.Submit_button.setStyleSheet("color : rgb(255, 255, 255);\n"
"background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 14pt;\n"
"\n"
"border-radius : 16px;")
        self.Submit_button.setObjectName("Submit_button")
        self.locate_3 = QtWidgets.QLineEdit(self.widget)
        self.locate_3.setGeometry(QtCore.QRect(50, 420, 300, 41))
        self.locate_3.setStyleSheet("color : rgba(0, 0, 0, 240);\n"
"background-color : rgba(0, 0, 0, 0);\n"
"\n"
"font-size:11pt;\n"
"font-family : \'Dosis\';")
        self.locate_3.setText("")
        self.locate_3.setObjectName("locate_3")
        self.locate_1 = QtWidgets.QLineEdit(self.widget)
        self.locate_1.setGeometry(QtCore.QRect(50, 240, 300, 41))
        self.locate_1.setStyleSheet("color : rgba(0, 0, 0, 240);\n"
"background-color : rgba(0, 0, 0, 0);\n"
"\n"
"font-size:11pt;\n"
"font-family : \'Dosis\';")
        self.locate_1.setText("")
        self.locate_1.setObjectName("locate_1")
        self.locate_2 = QtWidgets.QLineEdit(self.widget)
        self.locate_2.setGeometry(QtCore.QRect(50, 330, 300, 41))
        self.locate_2.setStyleSheet("color : rgba(0, 0, 0, 240);\n"
"background-color : rgba(0, 0, 0, 0);\n"
"\n"
"font-size:11pt;\n"
"font-family : \'Dosis\';")
        self.locate_2.setText("")
        self.locate_2.setObjectName("locate_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 210, 91, 41))
        self.label.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"font-weight : 600;\n"
"font-family : \'Dosis\';\n"
"font-size : 10pt;")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 390, 91, 41))
        self.label_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"font-weight : 600;\n"
"font-family : \'Dosis\';\n"
"font-size : 10pt;")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(30, 300, 91, 41))
        self.label_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"font-weight : 600;\n"
"font-family : \'Dosis\';\n"
"font-size : 10pt;")
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(50, 280, 300, 1))
        self.line.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(50, 370, 300, 1))
        self.line_2.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(50, 460, 300, 1))
        self.line_3.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Where?"))
        self.Submit_button.setText(_translate("Dialog", "Submit"))
        self.locate_3.setPlaceholderText(_translate("Dialog", "Location 3"))
        self.locate_1.setPlaceholderText(_translate("Dialog", "Location 1"))
        self.locate_2.setPlaceholderText(_translate("Dialog", "Location 2"))
        self.label.setText(_translate("Dialog", "Locate 1:"))
        self.label_5.setText(_translate("Dialog", "Locate 3:"))
        self.label_3.setText(_translate("Dialog", "Locate 2:"))
