# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\uri42\Desktop\Date-Manger\Dummy Files\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(900, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        dialog.setFont(font)
        dialog.setWindowOpacity(-1.0)
        dialog.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(223, 95, 159, 200), stop:0.513812 rgba(224, 212, 107, 200), stop:1 rgba(103, 188, 228, 200));")
        self.widget_2 = QtWidgets.QWidget(dialog)
        self.widget_2.setGeometry(QtCore.QRect(250, 60, 400, 700))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius : 10px;")
        self.widget_2.setObjectName("widget_2")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(50, 295, 300, 1))
        self.line.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setGeometry(QtCore.QRect(50, 395, 300, 1))
        self.line_2.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(100, 630, 200, 40))
        self.label_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"font-weight : 600;\n"
"font-family : \'Dosis\';\n"
"font-size : 10pt;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(150, 390, 200, 40))
        self.label_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"font-weight : 600;\n"
"font-family : \'Dosis\';\n"
"font-size : 10pt;")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setGeometry(QtCore.QRect(60, 267, 8, 8))
        self.line_3.setStyleSheet("background-color: rgba(0, 0, 0, 120);\n"
"\n"
"border-radius : 50px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setGeometry(QtCore.QRect(60, 367, 8, 8))
        self.line_4.setStyleSheet("background-color: rgba(0, 0, 0, 120);\n"
"\n"
"border-radius : 50px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(55, 220, 200, 40))
        self.label_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"font-weight : 600;\n"
"font-family : \'Dosis\';\n"
"font-size : 10pt;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.PW = QtWidgets.QLineEdit(self.widget_2)
        self.PW.setGeometry(QtCore.QRect(90, 350, 260, 40))
        self.PW.setStyleSheet("color : rgba(0, 0, 0, 240);\n"
"background-color : rgba(0, 0, 0, 0);\n"
"\n"
"font-size:11pt;\n"
"font-family : \'Dosis\';")
        self.PW.setText("")
        self.PW.setFrame(False)
        self.PW.setClearButtonEnabled(False)
        self.PW.setObjectName("PW")
        self.Login_button = QtWidgets.QPushButton(self.widget_2)
        self.Login_button.setGeometry(QtCore.QRect(50, 470, 300, 40))
        self.Login_button.setStyleSheet("color : rgb(255, 255, 255);\n"
"background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 14pt;\n"
"\n"
"border-radius : 16px;")
        self.Login_button.setCheckable(False)
        self.Login_button.setObjectName("Login_button")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(100, 60, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color : rgb(0, 0, 0);\n"
"background-color : rgb(255, 255, 255);\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 26pt; ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(55, 320, 200, 40))
        self.label_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"font-weight : 600;\n"
"font-family : \'Dosis\';\n"
"font-size : 10pt;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.ID = QtWidgets.QLineEdit(self.widget_2)
        self.ID.setGeometry(QtCore.QRect(90, 250, 260, 40))
        self.ID.setStyleSheet("color : rgba(0, 0, 0, 240);\n"
"background-color : rgba(0, 0, 0, 0);\n"
"\n"
"font-size:11pt;\n"
"font-family : \'Dosis\';")
        self.ID.setText("")
        self.ID.setFrame(False)
        self.ID.setObjectName("ID")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.label_4.setText(_translate("dialog", "Or Sign Up"))
        self.label_5.setText(_translate("dialog", "Forgot Password?"))
        self.label_2.setText(_translate("dialog", "Username"))
        self.PW.setPlaceholderText(_translate("dialog", "Password"))
        self.Login_button.setText(_translate("dialog", "Login"))
        self.label.setText(_translate("dialog", "Login"))
        self.label_3.setText(_translate("dialog", "PW"))
        self.ID.setPlaceholderText(_translate("dialog", "User Name"))
