# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\uri42\Desktop\Date-Manger\Dummy Files\showResult.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1250, 480)
        Dialog.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(223, 95, 159, 200), stop:0.513812 rgba(224, 212, 107, 200), stop:1 rgba(103, 188, 228, 200))")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius : 10px;")
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.result_table_1 = QtWidgets.QTableWidget(self.widget)
        self.result_table_1.setStyleSheet("border : 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 10pt;\n"
"\n"
"border-radius : 12px;")
        self.result_table_1.setObjectName("result_table_1")
        self.result_table_1.setColumnCount(0)
        self.result_table_1.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.result_table_1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.result_table_2 = QtWidgets.QTableWidget(self.widget)
        self.result_table_2.setStyleSheet("border : 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 10pt;\n"
"\n"
"border-radius : 12px;")
        self.result_table_2.setObjectName("result_table_2")
        self.result_table_2.setColumnCount(0)
        self.result_table_2.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.result_table_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.result_table_3 = QtWidgets.QTableWidget(self.widget)
        self.result_table_3.setStyleSheet("border : 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 10pt;\n"
"\n"
"border-radius : 12px;")
        self.result_table_3.setObjectName("result_table_3")
        self.result_table_3.setColumnCount(0)
        self.result_table_3.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.result_table_3)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.loadData_button = QtWidgets.QPushButton(self.widget)
        self.loadData_button.setStyleSheet("color : rgb(255, 255, 255);\n"
"background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 14pt;\n"
"\n"
"border-radius : 16px;")
        self.loadData_button.setObjectName("loadData_button")
        self.horizontalLayout_4.addWidget(self.loadData_button)
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.save_image_button = QtWidgets.QPushButton(self.widget)
        self.save_image_button.setStyleSheet("color : rgb(255, 255, 255);\n"
"background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(223, 185, 204, 255), stop:0.510989 rgba(224, 219, 177, 255), stop:1 rgba(148, 202, 228, 255));\n"
"\n"
"font-family : \'Dosis\';\n"
"font-weight : bold;\n"
"font-size : 14pt;\n"
"\n"
"border-radius : 16px;")
        self.save_image_button.setObjectName("save_image_button")
        self.horizontalLayout_4.addWidget(self.save_image_button)
        spacerItem7 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loadData_button.setText(_translate("Dialog", "Load Data"))
        self.save_image_button.setText(_translate("Dialog", "Save as Image"))
